build:
    environment:
        php:
            version: 5.6.9
    dependencies:
        before:
            - curl -s http://getcomposer.org/installer | php
            - php scripts/test-with-laravel.php 5.1
filter:
    paths:
        - lib/*